ShopBanDongHo/Areas/Admin/Controllers/AdminHomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ShopBanDongHo.Models;
using ShopBanDongHo.ModelData;
namespace ShopBanDongHo.Areas.Admin.Controllers
{
    public class AdminHomeController : Controller
    {
        // GET: Admin/AdminHome
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult ListHoaDon()
        {
            return View();
        }
        public ActionResult ListCompany()
        {
            return View();
        }
        public ActionResult CreateCompany()
        {
            return View();
        }
        public ActionResult Chart()
        {
            return View();
        }
        QuanLiDongHoEntities db = new QuanLiDongHoEntities();

        [HttpGet]
        public ActionResult CreateBlog()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateBlog(tBlog blog)//tao 1 lop blog
        {//Tao  1 menu blog
            if (blog.TieuDe == null)
            {
                ViewBag.GuiBlog = "";
                return View(blog);
            }
            if (blog.TenNgPost == null || blog.AnhBlog == null || blog.AnhBlogNho == null)
            {
                ViewBag.GuiBlog = "";
                return View(blog);
            }

            string MaBlogs = (Int32.Parse(db.Blogs.OrderByDescending(n => n.MaBlog).FirstOrDefault().MaBlog.Replace("MB", "")) + 1).ToString();
            if (MaBlogs.Length == 1)
            {
                MaBlogs = "0" + MaBlogs;
            }
            Blog newblog = new Blog();
            newblog.MaBlog = "MB" + MaBlogs;
            newblog.TieuDe = blog.TieuDe;
            newblog.NgPost = blog.TenNgPost;
            newblog.ThoiGian = DateTime.Now;
            newblog.AnhBlog = blog.AnhBlog;
            newblog.AnhBlog_nho = blog.AnhBlogNho;
            newblog.NoiDung = blog.NoiDung;

            db.Blogs.Add(newblog);
            db.SaveChanges();
            ViewBag.GuiBlog = "oke";

            return View();
        }
    }
}

ShopBanDongHo/Controllers/ChartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using ShopBanDongHo.Models;
using ShopBanDongHo.ModelData;

namespace ShopBanDongHo.Controllers
{

    public class ChartController : ApiController
    {
        QuanLiDongHoEntities db = new QuanLiDongHoEntities();
        public IEnumerable<tDoanhThu> GetallDoangThu()
        {
            IList<tDoanhThu> tongdoanhthu = new List<tDoanhThu>();

            var sell = db.DoanhThus
                 .GroupBy(a => a.TenNhanVien)
    .Select(a => new { Amount = a.Sum(b => b.DoanhThuNV), Name = a.Key })
    .OrderByDescending(a => a.Amount)
    .ToList();

            foreach (var item in sell)
            {
                tongdoanhthu.Add(new tDoanhThu
                {
                    tennhanvien = item.Name,
                    tongdoanhthu = (int)item.Amount

                });
            }

            return tongdoanhthu;
        }

    }
}

ShopBanDongHo/Areas/Admin/Views/AdminHome/Chart.cshtml
@{
    ViewBag.Title = "Chart";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}


<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<script src="~/Scripts/jquery-3.4.1.min.js"></script>
<div>
    <canvas id="myChart"></canvas>
</div>
<script>
    $.ajax({
        url: 'https://localhost:44374/api/Chart',
        method: 'GET',
        contentType: 'application/json',
        success: function (datas) {
            console.log(datas)
            const ten = [];
            var tien = [];
            for (var i = 0; i < datas.length; i++) {
                ten.push(datas[i].tennhanvien)
                tien.push(datas[i].tongdoanhthu)
            }
            console.log(ten)
            console.log(tien)



            const labels = [
                'January',
                'February',
                'March',
                'April',
                'May',
                'June',
            ];
            const data = {
                labels: ten,
                datasets: [{
                    label: 'Tổng doanh thu của nhân viên',
                    backgroundColor: 'rgb(255, 99, 132)',
                    borderColor: 'rgb(255, 99, 132)',
                    data: tien,
                }]
            };
            const config = {
                type: 'bar',
                data,
                options: {}
            };

            var myChart = new Chart(
                document.getElementById('myChart'),
                config
            );

        }
    });
    // === include 'setup' then 'config' above ===
    
</script>

ShopBanDongHo/Areas/Admin/Views/AdminHome/CreateBlog.cshtml
@{
    ViewBag.Title = "CreateBlog";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}


<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,700,900&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="~/Assets/BlogAdminLayout/fonts/icomoon/style.css">


    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="~/Assets/BlogAdminLayout/css/bootstrap.min.css">

    <!-- Style -->
    <link rel="stylesheet" href="~/Assets/BlogAdminLayout/css/style.css">

    <title>Contact Form #6</title>
</head>
<body>
    <br />
    <br />
    <div class="content">

        <div class="container">
            <div class="row justify-content-center">
                <div class="col-md-10">


                    <div class="row justify-content-center">
                        <div class="col-md-6">

                            <h3 class="heading mb-4">Let's talk about everything!</h3>

                            <p><img src="~/Assets/BlogAdminLayout/images/undraw-contact.svg" alt="Image" class="img-fluid"></p>


                        </div>
                        <div class="col-md-6">

                            @using (Html.BeginForm("CreateBlog", "AdminHome", FormMethod.Post, new { @class = "mb-5", @id = "contactForm", @name = "contactForm" }))
                            {
                                <div class="row">
                                    <div class="col-md-12 form-group">
                                        <input type="text" class="form-control" name="TieuDe" id="name" placeholder="Tiêu đề">
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-12 form-group">
                                        <input type="text" class="form-control" name="TenNgPost" id="email" placeholder="Người đăng">
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-12 form-group">
                                        <input type="file" class="form-control" name="AnhBlog" placeholder="Ảnh dưới 50 ký tự">
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-12 form-group">
                                        <input type="file" class="form-control" name="AnhBlogNho" id="subject" placeholder="Ảnh dưới 50 ký tự">
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-12 form-group">
                                        <textarea name="NoiDung" class="form-control" id="message" cols="30" rows="7" placeholder="Nhập nội dung"></textarea>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-12">
                                        <input type="submit" value="Create Blog" class="btn btn-primary rounded-0 py-2 px-4">
                                        <span class="submitting"></span>
                                    </div>
                                </div>
                            }

                            <div id="form-message-warning mt-4"></div>
                            <div id="form-message-success">
                                Your message was sent, thank you!
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>



    <script src="~/Assets/BlogAdminLayout/js/jquery-3.3.1.min.js"></script>
    <script src="~/Assets/BlogAdminLayout/js/popper.min.js"></script>
    <script src="~/Assets/BlogAdminLayout/js/bootstrap.min.js"></script>
    <script src="~/Assets/BlogAdminLayout/js/jquery.validate.min.js"></script>
    <script src="~/Assets/BlogAdminLayout/js/main.js"></script>

</body>
</html>

ShopBanDongHo/Areas/Admin/Views/AdminHome/CreateCompany.cshtml
@{
    ViewBag.Title = "CreateCompany";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Tạo chi nhánh</h2>
<div class="container">
    <form class="col-sm-6">
        <label class="col-sm-4">Tên công ty</label> <input class="row-cols-6" /><br />
        <label class="col-sm-4">Địa chỉ</label> <input class="row-cols-6" /><br />
        <label class="col-sm-4">Số điện thoại</label> <input class="row-cols-6" /><br />
        <input type="submit" onclick="newCompany()" value="Thêm công ty"/>

    </form>
</div>
<script type="text/javascript">
    function newCompany() {
        alert('');
   
    }

</script>

ShopBanDongHo/Areas/Admin/Views/AdminHome/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Index</h2>

ShopBanDongHo/Areas/Admin/Views/AdminHome/ListCompany.cshtml
@{
    ViewBag.Title = "ListCompany";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}
<h2>Danh sách công ty</h2>
<div class="container">
    <p>
        <button type="button" id="TaoMoi" data-toggle="modal" data-target="#myModal" onclick="createCompanyNew()">Tạo mới chi nhánh</button>
    </p>
    <input type="text" placeholder="tìm kiếm theo tên Công ty" id="NameSearch" />
    <input type="submit" onclick="searchName()" />
    <table class="table">
        <tr>
            <th>
                Tên công ty
            </th>
            <th>
                Dịa chỉ
            </th>
            <th>
                Số điện thoại
            </th>
            <th></th>
        </tr>
        <tbody id="allCty"></tbody>

    </table>
    <div class="container">
        <!-- Modal -->
        <div class="modal fade" id="myModal" role="dialog">
            <div class="modal-dialog">

                <!-- Modal content-->
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                        <h4 class="modal-title">Tạo chi nhánh</h4>
                    </div>
                    <div class="modal-body">
                        <div><label class="col-sm-4">  Tên công ty</label><input id="TenCTy" /></div>
                        <div><label class="col-sm-4">   Dịa chỉ</label><input id="DiaChi" /></div>
                        <div><label class="col-sm-4">   Số điện thoại</label><input id="SoDT" /></div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default edit" data-dismiss="modal" onclick="createCompany()">Tạo mới</button>
                        <button type="button" class="btn btn-default" data-dismiss="modal">Đóng</button>
                    </div>
                </div>

            </div>
        </div>

    </div>



</div>
<script src="~/Scripts/jquery-3.4.1.min.js"></script>
<script type="text/javascript">
    $(document).ready(function () {
        loadAllCompany();

    });
    function loadAllCompany() {

        var str = '';
        $.ajax({
            type: 'GET',
            url: 'https://localhost:44374/api/company',
            dataType: 'json',
            success: function (data) {
                console.log(data);
                $.each(data, function (key, val) {
                    str += '<tr class="ChiTiet"><td>' + val.TenCty + '</td><td>' + val.DiaChi + '</td><td>' + val.SoDT
                        + '</td><td><button type="button" onclick="EditCompany(' + "'" + val.TenCTy + "'" + ')" data-toggle="modal" data-target="#myModal">Chỉnh sửa</button></td></tr>';
                });

                $('#allCty').html(str);
            },
            error: function (xhr) {
                alert(xhr.responseText);
            }
        });

    }
    function searchName() {
        //alert(document.getElementById("NameSearch").value);
        var datas = document.getElementById("NameSearch").value;
        //console.log(datas)
        if (datas == '') {
            alert('vui long nhap ten can tim');
            loadAllCompany();
        }
        else {
            var strs = '';
            $.ajax({
                type: 'GET',
                url: 'https://localhost:44374/api/Company/GetAllCongty/?id=' + datas,
                dataType: 'json',
                success: function (data) {
                    console.log(data);
                    $('#allHoaDon').empty();
                    $.each(data, function (key, val) {
                        strs += '<tr class="ChiTiet"><td>' + val.TenCty + '</td><td>' + val.DiaChi + '</td><td>' + val.SoDT
                            + '</td><td><button type="button" onclick="EditCompany(' + "'" + val.TenCTy + "'" + ')" data-toggle="modal" data-target="#myModal">Chỉnh sửa</button></td></tr>';
                    });

                    $('#allCty').html(strs);//nho bao sua
                },
                error: function (xhr) {
                    alert(xhr.responseText);
                }
            });
            $("#clicks").click(function () {
                alert("The paragraph was clicked.");
            });
        }

    }

    //
    function createCompanyNew() {
        $(".edit").empty();
        $(".edit").text("Tạo mới");
        $("#TenCTy").attr('readonly', false);
        $(".edit").attr('onclick', 'createCompany()');
        document.getElementById("TenCTy").value = "";
        document.getElementById("DiaChi").value = "";
        document.getElementById("SoDT").value = "";
    }


    function createCompany() {

        var TenCTy = document.getElementById("TenCTy").value;
        var DiaChi = document.getElementById("DiaChi").value;
        var SoDT = document.getElementById("SoDT").value;

        if (TenCTy == '' || DiaChi == '' || SoDT == '') {
            alert('Vui lòng nhập đầy đủ các trường')
        }
        else {
            $.ajax({
                type: 'POST',
                url: 'https://localhost:44374/api/company/?tenCty=' + TenCTy + '&Diachi=' + DiaChi + '&SoDT=' + SoDT,
                dataType: 'json',
                success: function (data) {
                    if (data == true) {
                        alert('Tạo thành công');
                        loadAllCompany();
                    }

                    else
                        alert('Tạo thất bại!! Tên công ty Đã bị trùng');

                }
            });


        }




    }

    function EditCompany(id) {
        $("tr").click(function () {
            var TenCTy = $(this).closest('.ChiTiet').find('td:nth-child(1)').text();
            var DiaChi = $(this).closest('.ChiTiet').find('td:nth-child(2)').text();
            var SoDT = $(this).closest('.ChiTiet').find('td:nth-child(3)').text();
            //console.log(TenCTy);
            //console.log(DiaChi);
            //console.log(SoDT);


            document.getElementById("TenCTy").value = TenCTy;
            $("#TenCTy").attr('readonly', true);
            document.getElementById("DiaChi").value = DiaChi;
            document.getElementById("SoDT").value = SoDT;


            $(".edit").empty();
            $(".edit").text("Lưu chỉnh sửa");
            $(".edit").attr('onclick', 'confirms()');




        });


    }
    function confirms() {
        var TenCTy = document.getElementById("TenCTy").value;
        var DiaChi = document.getElementById("DiaChi").value;
        var SoDT = document.getElementById("SoDT").value;
        //console.log(TenCTy);
        //console.log(DiaChi);
        //console.log(SoDT);


        if (TenCTy == '' || DiaChi == '' || SoDT == '') {
            alert('Vui lòng nhập đầy đủ các trường')
        }
        else {
            $.ajax({
                type: 'PUT',
                url: 'https://localhost:44374/api/company/?tenCty=' + TenCTy + '&Diachi=' + DiaChi + '&SoDT=' + SoDT,
                dataType: 'json',
                success: function (data) {
                    if (data == true) {
                        alert('Sửa thành công');
                        loadAllCompany();
                    }

                    else
                        alert('Sửa thất bại!!');

                }
            });


        }


    }
</script>

ShopBanDongHo/Areas/Admin/Views/AdminHome/ListHoaDon.cshtml
@model IEnumerable<ShopBanDongHo.Models.HoaDon>

@{
    ViewBag.Title = "";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Danh sách hóa đơn</h2>

@*<p>
        @Html.ActionLink("Create New", "Create")
    </p>*@

<input type="text" placeholder="tìm kiếm theo địa chỉ nhận hàng" id="NameSearch" />
<input type="submit" onclick="searchName()" />
<div class="container">
    <table class="table">
        <tr>
            <th>
                Mã hóa đơn
            </th>
            <th>
                Mã khách hàng
            </th>
            <th>
                Ngày đặt hàng
            </th>
            <th>
                Người nhận
            </th>
            <th>
                Số điện thoại nhận
            </th>
            <th>
                Địa chỉ nhận hàng
            </th>
            <th>
                Email liên hệ
            </th>
            <th></th>
        </tr>
        <tbody id="allHoaDon"></tbody>

    </table>



    <!-- Trigger the modal with a button -->
    <!-- Modal -->
    <div class="modal fade" id="myModal" role="dialog">
        <div class="modal-dialog">

            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Chi tiết hóa đơn</h4>
                </div>
                <div class="modal-body">
                    <label>Dịa chỉ nhận : </label><p id="diachi"></p>
                    <label>Người nhận : </label><p id="NguoiNhan"></p>
                    <label>Số điện thoại : </label><p id="SoDienThoai"></p>
                    <label>Tổng tiền </label><p id="TongTien"></p>
                    <p>Chi tiết sản phẩm</p>
                    <div>
                        <table>
                            <tr>
                                <th>Mã hóa đơn</th>
                                <th>Mã sản phẩm</th>
                                <th>Tên sản phẩm</th>
                                <th>Số lượng</th>
                                <th>Giá</th>

                            </tr>
                            <tbody id="ChiTietHoaDon"></tbody>

                        </table>


                    </div>


                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" onclick="loadAll()" data-dismiss="modal">Close</button>
                </div>
            </div>

        </div>
    </div>

</div>


@*test*@
<script src="~/Scripts/jquery-3.4.1.min.js"></script>
<script type="text/javascript">
    $(document).ready(function () {
        loadAll();
    });
    function loadAll() {
        var str = '';
        $.ajax({
            type: 'GET',
            url: 'https://localhost:44374/api/Bills',
            dataType: 'json',
            success: function (data) {
                console.log(data);
                $.each(data, function (key, val) {
                    str += '<tr class="ChiTiet"><td>' + val.MaHD + '</td><td>'
                        + val.MaKH + '</td><td>' + val.NgayTao + '</td><td>' + val.ShipName + '</td><td>'
                        + val.ShipMobile + '</td><td>' + val.ShipAdress + '</td><td>' + val.ShipEmail
                        + '</td><td><button type="button" onclick="Chitiethoadon(' + "'" + val.MaHD + "'" + ')" data-toggle="modal" data-target="#myModal">Chi tiết</button></td></tr>';
                });

                $('#allHoaDon').html(str);
            },
            error: function (xhr) {
                alert(xhr.responseText);
            }
        });


    }
    function searchName() {
        //alert(document.getElementById("NameSearch").value);
        var datas = document.getElementById("NameSearch").value;
        //console.log(datas)
        if (datas == '') {
            alert('vui long nhap ten can tim');
            loadAll();
        }
        else {
            var strs = '';
            $.ajax({
                type: 'GET',
                url: 'https://localhost:44374/api/bills/GetHoaDonsbyname/?id=' + datas,
                dataType: 'json',
                success: function (data) {
                    console.log(data);
                    $('#allHoaDon').empty();
                    $.each(data, function (key, val) {
                        strs += '<tr><td>' + val.MaHD + '</td><td>'
                            + val.MaKH + '</td><td>' + val.NgayTao + '</td><td>' + val.ShipName + '</td><td>'
                            + val.ShipMobile + '</td><td>' + val.ShipAdress + '</td><td>' + val.ShipEmail
                            + '</td><td><button type="button" onclick="Chitiethoadon(' + "'" + val.MaHD + "'" + ')" data-toggle="modal" data-target="#myModal">Chi tiết</button></td></tr>';
                    });

                    $('#allHoaDon').html(strs);
                },
                error: function (xhr) {
                    alert(xhr.responseText);
                }
            });
            $("#clicks").click(function () {
                alert("The paragraph was clicked.");
            });
        }

    }

    function Chitiethoadon(id) {
        var tongtien = 0;
        console.log(id);
        var strct = '';
        $.ajax({
            type: 'GET',
            url: 'https://localhost:44374/GetChitetHoaDon/' + id,
            dataType: 'json',
            success: function (data) {
                console.log(data);

                $.each(data, function (key, val) {
                    strct += '<tr><td>' + val.MaHD + '</td><td>'
                        + val.MaSP + '</td><td>' + val.TenSP + '</td><td>' + val.SoLuong + '</td><td>'
                        + val.TongTien + '</td></tr>';

                    tongtien += val.TongTien;
                });
                console.log(tongtien);
                $("#TongTien").empty();
                document.getElementById("TongTien").append(tongtien);
                $('#ChiTietHoaDon').html(strct);
            },
            error: function (xhr) {
                alert(xhr.responseText);
            }
        });

        $("tr").click(function () {
            var DiaChi = $(this).closest('.ChiTiet').find('td:nth-child(6)').text();
            var SoDienThoai = $(this).closest('.ChiTiet').find('td:nth-child(5)').text();
            var NguoiNhan = $(this).closest('.ChiTiet').find('td:nth-child(4)').text();
            $("#diachi").empty();
            $("#NguoiNhan").empty();
            $("#SoDienThoai").empty();

            document.getElementById("diachi").append(DiaChi);
            document.getElementById("NguoiNhan").append(NguoiNhan);
            document.getElementById("SoDienThoai").append(SoDienThoai);




        });
    }
</script>